name: "Build and Deploy - Flutter Web"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # Langkah 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Langkah 2: Build Flutter Web
      - name: Build Flutter Web
        run: |
          flutter clean
          flutter pub get
          flutter build web --release

      # Langkah 3: Deploy ke IIS
      - name: Deploy to IIS
        run: |
          cd C:\inetpub\wwwroot\Crud-Testing
          xcopy /s /e /y ${{ github.workspace }}\build\web\* .
