name: "Build and Deploy - Flutter Web"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # Langkah 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Langkah 2: Tambahkan Flutter ke PATH
      - name: Add Flutter to PATH
        run: |
          $env:PATH += ";C:\flutter\bin"
          flutter doctor

      # Langkah 3: Build Flutter Web
      - name: Build Flutter Web
        run: |
          flutter clean
          flutter pub get
          flutter build web --release

      # Langkah 4: Salin Build ke Folder Target (Opsional)
      - name: Deploy to IIS
        run: |
          xcopy /s /e /y "${{ github.workspace }}\build\web\*" "C:\inetpub\wwwroot\Crud-Testing"
