name: "Build and Deploy - Flutter Web"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # Langkah 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Langkah 2: Tambahkan Flutter ke PATH
      - name: Add Flutter to PATH
        run: |
          $env:PATH += ";C:\flutter\bin"
          flutter doctor

      # Langkah 3: Build Flutter Web
      - name: Build Flutter Web
        run: |
          C:\flutter\bin\flutter clean
          C:\flutter\bin\flutter pub get
          C:\flutter\bin\flutter build web --release

      # Langkah 4: Deploy ke IIS
      - name: Deploy to IIS
        run: |
          cd C:\inetpub\wwwroot\Crud-Testing
          xcopy /s /e /y ${{ github.workspace }}\build\web\* .
